#!/usr/bin/env bash
# Installed by slate. Edit to add project-specific setup.
set -euo pipefail

echo "[init.sh] starting..."

mkdir -p docs/slate/progress/subagents docs/slate/features

_create_if_missing() {
  local file="$1" header="$2"
  if [ ! -s "$file" ]; then
    printf '%s\n' "$header" > "$file"
    echo "[init.sh] created $file"
  fi
}

_create_if_missing "docs/slate/progress/current.md" "# Current work

_(none in flight)_"

_create_if_missing "docs/slate/progress/history.md" "# Session history
"

_create_if_missing "docs/slate/features/backlog.md" "# Backlog
"

_create_if_missing "docs/slate/features/in-progress.md" "# In progress
"

_create_if_missing "docs/slate/features/done.md" "# Done

<!-- FORBIDDEN to edit existing entries. Create a successor with Supersedes: FEAT-XXX. -->
"

# Detect tooling and run lightweight setup (non-fatal)
[ -f package.json ] && command -v node >/dev/null 2>&1 && \
  { echo "[init.sh] node project; npm install..."; npm install --silent 2>/dev/null || true; }

[ -f Cargo.toml ] && command -v cargo >/dev/null 2>&1 && \
  { echo "[init.sh] rust project; cargo check..."; cargo check --quiet 2>/dev/null || true; }

[ -f go.mod ] && command -v go >/dev/null 2>&1 && \
  { echo "[init.sh] go project; go mod download..."; go mod download 2>/dev/null || true; }

# Generate codebase map (always regenerated)
_codebase_map() {
  local out="docs/slate/progress/codebase-map.md"
  local now; now=$(date '+%Y-%m-%d %H:%M' 2>/dev/null || date)
  local tree_output
  if command -v tree >/dev/null 2>&1; then
    tree_output=$(tree -L 3 -a \
      -I 'node_modules|.git|__pycache__|.venv|venv|.next|dist|build|.claude' 2>/dev/null || true)
  else
    tree_output=$(find . -maxdepth 3 \
      \( -path '*/node_modules' -o -path '*/.git' -o -path '*/__pycache__' \
         -o -path '*/.venv' -o -path '*/venv' -o -path '*/.next' \
         -o -path '*/dist' -o -path '*/build' -o -path '*/.claude' \) -prune -o -print 2>/dev/null | sort)
  fi
  {
    echo "# Codebase Map"
    echo "> Auto-generated by init.sh — $now"
    echo ""
    echo '```'
    echo "$tree_output"
    echo '```'
  } > "$out"
  echo "[init.sh] codebase map -> $out"
}
_codebase_map

echo "[init.sh] OK"
